scality/Zenko

swarm-production/README.md
swarm-testing/README.md

When using aws cli with Zenko, if the port is still the default 80, it
should not be specified under the `--endpoint` option.

DOC: Highlight default port should not be explicit

---

swarm-production/docker-stack.yml

The kafka container would store its log in a variable-name directory inside the volume

Fix Kafka log dir, lower kafka memory allocation

---

helm/zenko/charts/cloudserver-front/templates/deployment.yaml
helm/zenko/charts/cloudserver-front/values.yaml
helm/zenko/charts/mongodb-replicaset/.helmignore
helm/zenko/charts/mongodb-replicaset/Chart.yaml
helm/zenko/charts/mongodb-replicaset/README.md
helm/zenko/charts/mongodb-replicaset/mongodb-up-test.sh
helm/zenko/charts/mongodb-replicaset/templates/NOTES.txt
helm/zenko/charts/mongodb-replicaset/templates/_helpers.tpl
helm/zenko/charts/mongodb-replicaset/templates/mongodb-admin-secret.yaml
helm/zenko/charts/mongodb-replicaset/templates/mongodb-ca.yaml
helm/zenko/charts/mongodb-replicaset/templates/mongodb-configmap.yaml
helm/zenko/charts/mongodb-replicaset/templates/mongodb-keyfile-secret.yaml
helm/zenko/charts/mongodb-replicaset/templates/mongodb-service.yaml
helm/zenko/charts/mongodb-replicaset/templates/mongodb-statefulset.yaml
helm/zenko/charts/mongodb-replicaset/templates/tests/mongodb-up-test-configmap.yaml
helm/zenko/charts/mongodb-replicaset/templates/tests/mongodb-up-test-pod.yaml
helm/zenko/charts/mongodb-replicaset/test.sh
helm/zenko/charts/mongodb-replicaset/values.yaml
helm/zenko/values.yaml

I have left it disabled by default but can be enabled simply in the zenko/values.yml or with the `--set mongodb-replicaset.enabled=true` flag when deploying

ZENKO-9 Replicaset Compatibility

---

helm/zenko/charts/cloudserver-front/templates/deployment.yaml
helm/zenko/charts/mongodb-replicaset/init/Dockerfile
helm/zenko/charts/mongodb-replicaset/init/Makefile
helm/zenko/charts/mongodb-replicaset/init/files/install.sh
helm/zenko/charts/mongodb-replicaset/init/files/on-start.sh
helm/zenko/charts/mongodb-replicaset/templates/mongodb-service.yaml
helm/zenko/charts/mongodb-replicaset/templates/mongodb-statefulset.yaml
helm/zenko/charts/mongodb-replicaset/templates/tests/mongodb-up-test-pod.yaml
helm/zenko/charts/mongodb-replicaset/values.yaml
helm/zenko/values.yaml

In 6d6ae5bd9f044ad9e5e30b607b1fd6692df7ec24, the MongoDB ReplicaSet Chart from the upstream stable channel was imported, though with some minor modifications.
This commit
- Reverts those modification, such that the imported Chart now matches upstream
- Gets rid of the modifications made to the upstream Chart in 846e48b91485eec58c1a1908e409a91fff47eee3 because they're not necessary
- Changes the top-level Chart's `values.yaml` to get back the desired configuration, and updates changes to the `cloudserver-front` deployment accordingly.
Note `values.yaml` now contains a couple of values which are not strictly required to be present. Instead, later on, we could use 'import values' (https://github.com/kubernetes/helm/blob/master/docs/charts.md#using-the-child-parent-format).

Fix MongoDB ReplicaSet sub-chart and integration

---

charts/value-dev.yml
charts/zenko/requirements.lock
charts/zenko/requirements.yaml

Also update `value-dev.yml` accordingly, since the upstream changed some
value definitions.
See: https://github.com/scality/zenko-zookeeper/pull/7
See: https://github.com/scality/zenko-zookeeper/pull/7/commits/355ccd6d6c7c233034455baa8071ddf4e5d5a34d

feat(chart): update to `zenko-zookeeper` 0.0.6

---

charts/cloudserver-front/Chart.yaml
charts/cloudserver-front/templates/tests/cloudserver-front-test.yaml
charts/zenko/requirements.lock
charts/zenko/requirements.yaml

This commit adds a very basic Helm test, only enabled when Orbit
integration is disabled, which performs an `ls` against the deployed S3
endpoint using `aws-cli`.

feat(chart): add simple test-case to `cloudserver-front`

---

charts/zenko/requirements.lock
charts/zenko/requirements.yaml

This new version contains various fixes, of which kubernetes/charts#3684
is the most interesting, fixing cAdvisor metrics collection.
To view all changes, run
```shell
git log --reverse 702fb47980ddaa87c86b6e702c0067a94c959214..ddce4afd8d943d65feaf7cb73e6d6f5bd2a124ef stable/prometheus
```
in a clone of the Kubernetes Charts repository.
See: https://github.com/kubernetes/charts/pull/3684

feat(chart): upgrade upstream Prometheus Chart to 5.3.1

---

charts/zenko/requirements.lock
charts/zenko/requirements.yaml

No change in Zookeeper version, only some changes in the Chart:
- Enable `Parallel` Pod management, speeding up deployment
- Use the `RollingUpdate` strategy on the Deployment
- Unify JVM heap allocation and Kubernetes memory resource requests
See: https://github.com/scality/zenko-zookeeper/compare/v0.0.6...v0.0.7

Chart: Update zenko-zookeeper to 0.0.7

---

swarm-production/docker-stack.yml

The mongodb 3.6 service would kick itself out of the replicaset (REMOVED state) on laptop sleep, which does not happen with 3.4

Downgrade mongodb to 3.4

---

charts/value-dev.yml

All this stuff is not needed anymore...(But everyone need delete and recreate their cluster)
Note: not sure for zookeeper storage size, why 1G ?

Storageclass local-storage is enabled by default on new dev platform

---

tests/docker-entrypoint.sh
tests/tox.ini
tests/zenko_e2e/cloudserver/test_networking.py

These commits add a couple of new E2E tests, which simply validate the cluster is able to resolve Amazon S3 endpoints, and can connect to them, without TLS certificate problems.
As noted in the code, the tests use `xfail` in specific conditions: as an example, failure to resolve is not necessarily a problem in very constrained environments. We do, however, want to be made aware of this, especially when troubleshooting.

E2E: Basic networking sanity checks

---

charts/minikube.md

There are known issues with the current latest versions of helm and minikube
which is causing failures for new users trying to deploy zenko on minikube and
therefore explicitly declaring known working versions for future reference.
Issues with new versions of minikube
https://github.com/kubernetes/minikube/issues/2765
Issues with new versions of helm
https://github.com/kubernetes/helm/pull/3991

docs: Specify known working versions

---

charts/README.md
charts/cloudserver-front/values.yaml
charts/single-node-values.yml
charts/zenko/values.yaml

This allows Orbit to be enabled by default which is our normal for swarm and cloudserver.

ft: Unify charts with Orbit

---

charts/zenko/values.yaml

ZENKO-325
Changes the replica defaults to be 3 for mongoDB and kafka
(zookeeper already defaults to 3)

ft: Change default replicas

---

charts/backbeat/templates/consumer/deployment.yaml
charts/backbeat/templates/producer/deployment.yaml
charts/backbeat/values.yaml

This fixes replication not working on k8s. The reason being that the s3-metadata host isn't used anymore (MongoDB is used instead).

bf: fix replication on k8s

---

charts/backbeat/templates/replication/status_deployment.yaml
charts/backbeat/values.yaml

ZENKO-394
This adds the Replication Status Processor deployment to the backbeat
chart which is needed to write the status back to CloudServer.

ft: add replication status to backbeat

---

charts/backbeat/templates/tests/test-api-service.yml
charts/cloudserver-front/templates/tests/test-cloudserver-front-service.yml
charts/s3-data/templates/tests/test-s3-data-service.yml

These are very basic service tests. They essentially test that service works as an endpoint that properly connects to the underlying pods. These tests can be useful for catching bad port configurations.
An example of an official Kubernetes chart service test: https://github.com/kubernetes/charts/blob/master/stable/redis-ha/templates/tests/test-redis-sentinel-service.yaml
These tests are run as part of helm test. So to execute them just do:
```helm test zenko``` (assuming zenko is the name of your release) **OR**
```helm test zenko --cleanup``` to cleanup containers automatically.

ft: add service tests

---

charts/backbeat/templates/api/deployment.yaml
charts/backbeat/templates/replication/consumer_deployment.yaml
charts/backbeat/templates/replication/producer_deployment.yaml
charts/cloudserver-front/templates/deployment.yaml
charts/minikube.md
charts/single-node-values.yml
charts/zenko/requirements.lock
charts/zenko/requirements.yaml
charts/zenko/values.yaml

This PR adds redis sentinel to the Zenko stack. It is used (currently) by backbeat replication and backbeat api.

ft: helm chart for Redis Sentinel

---

charts/backbeat/templates/replication/status_deployment.yaml

ZENKO-420
Fixes bug that causes the replication status pod to perpetually crash
only with Orbit management enabled. However completely functional without management.

bf: fix rep status w/ orbit

---

charts/backbeat/values.yaml

Updating backbeat to this new image will prevent the replication populator pod from hanging when unable to connect to Kafka. Instead, this pod will crash, and Kubernetes will restart accordingly.

bf: update to latest backbeat image

---

charts/cloudserver-front/values.yaml
charts/s3-data/values.yaml

This new Cloudserver image will make the "RING with S3 Connector" backend work properly.

bf: fixes RING not working as backend

---

charts/cloudserver-front/templates/deployment.yaml
charts/cloudserver-front/values.yaml

This adds the ability to specify optional HTTP and HTTPS proxy endpoints for Cloudserver on its values.yml.

ft: add proxy support for egress to clouds

---

.github/ISSUE_TEMPLATE.md
README.md
charts/README.md
swarm-production/README.md
swarm-testing/README.md

I made the docs say the same things more clearly with fewer words.

Doc review

---

charts/gke.md

This guide adds details on how to install Zenko on an existing K8s
cluster hosted on Google Cloud.

Add guide to install Zenko on Google Kubernetes Engine

---

charts/cloudserver-front/templates/deployment.yaml

- LivenessProbe is for checking if the service is up: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ 
- We do not need deep health check for that because deep health check also checks the backend.
- Use Case for bug: If someone deletes their AWS bucket which was configured in orbit, kubernetes will try to restart the cloud server container because /_/healthcheck/deep will respond with an error.
- To check the service status we only need /_/healthcheck

bf: ZENKO-423 Remove deep healthcheck from livenessProbe

---

charts/backbeat/templates/_helpers.tpl
charts/backbeat/templates/api/deployment.yaml
charts/backbeat/templates/lifecycle/consumer_deployment.yaml
charts/backbeat/templates/lifecycle/producer_deployment.yaml
charts/backbeat/templates/replication/consumer_deployment.yaml
charts/backbeat/templates/replication/producer_deployment.yaml
charts/backbeat/templates/replication/status_deployment.yaml
charts/backbeat/values.yaml
charts/cloudserver-front/templates/_helpers.tpl
charts/cloudserver-front/templates/deployment.yaml
charts/cloudserver-front/values.yaml
charts/single-node-values.yml
charts/zenko/values.yaml

Before, the environmental variable MONGODB_HOSTS (which both Backbeat and Cloudserver-front use) was a hardcoded string of 3 MongoDB replica sets, like this:
```
{{ .Release.Name }}-mongodb-replicaset-0.{{ .Release.Name }}-mongodb-replicaset:27017,{{ .Release.Name }}-mongodb-replicaset-1.{{ .Release.Name }}-mongodb-replicaset:27017,{{ .Release.Name }}-mongodb-replicaset-2.{{ .Release.Name }}-mongodb-replicaset:27017
```
These changes will generate the proper MONGODB_HOSTS string based on the number of replicas sets specified in the charts/values.yaml file.
These changes also introduce the "nodeCount" anchor value, which serves as a base value for the number of replicas for the various deployments (MongoDB, Redis-HA, Zenko-Queue and Zenko-Quorum). Typically, this will be the number of …

feat: add support to change the number of mongodb replicas

---

eve/ci-values.yml
eve/main.yml

This stage tests the latest version of zenko's components (pushed into a private registry)
So as asked, I've renamed the build stage. to `latest` I can rename it if someone has a better idea. I'm not triggering automatically but we can do it. I just don't know where you want to trigger. I'm open to any suggestion, modifications, or even trash this code :D. Just ask ;)

ft: setting up latest stage ci job

---

eve/main.yml
eve/workers/zenko.yaml
tests/Makefile

I was afraid that using always latest tag on the e2e test image will not actually test zenko as we're not applying the same code if we modify the tests.
So I'm using the private registry to : 
```shell
build the image -> tag with the git sha1 -> push it to the private registry -> and pull it for testing
```
So the concept work! which is nice. But as suspected the tests are failing for now. I'll continue the work if you guys agree on this!
Thanks !

pushing and using e2e docker image on each build  

---

charts/backbeat/templates/gc/deployment.yaml

Make sure backbeat GC service uses mongodb-hosts template string for
MONGODB_HOSTS env var (adapts to number of mongodb hosts
automatically).

bugfix: ZENKO-143 mongodb-hosts for backbeat gc

---

charts/single-node-values.yml
charts/zenko-filer/.helmignore
charts/zenko-filer/Chart.yaml
charts/zenko-filer/nfsd.conf
charts/zenko-filer/templates/_helpers.tpl
charts/zenko-filer/templates/configmap.yaml
charts/zenko-filer/templates/deployment.yaml
charts/zenko-filer/templates/service.yaml
charts/zenko-filer/values.yaml
charts/zenko/requirements.lock
charts/zenko/requirements.yaml
charts/zenko/values.yaml

This adds the Zenko-Filer chart to Zenko, which you allows exporting buckets through NFS 🚀.
Zenko-Filer is made up of 3 components:
- Zenko-NFSD: Zenko's NFS server
- Zenko-MD: Zenko Metadata Gateway
- Portmap: RPC Server (rpcbind)
All of these are deployed in a 3 container pod (see ```zenko-filer/templates/deployment.yaml```).
NFS server and exports configuration is managed through a configmap, which reads from a file ```zenko-filer/nfsd.conf``` that can be modified (i.e to add new NFS exports). An upgrade (like ```helm upgrade``` for example), will then restart the NFS server with the updated configuration.

feat: add zenko-filer chart

---

charts/backbeat/templates/api/deployment.yaml

Backbeat API needs to make requests to fetch objectMD from backbeat metadata routes. These values need to be updated.

improvement: ZENKO-353 Avoid storing all objectMD

---

charts/cloudserver-front/values.yaml

Updating image tag for cloudserver with the latest fixes as of 07/01/2018

improvement: Update Cloudserver Image tag

---

charts/zenko/requirements.lock
charts/zenko/requirements.yaml

The new version of redis-ha adds default hard antiAffinity settings to both servers and sentinels to prevent them from being scheduled on the same nodes.

ft: Update redis-ha to latest version

---

tests/.dockerignore
tests/docker-entrypoint.sh
tests/tox.ini
tests/zenko_e2e/cloudserver/test_backbeat_metrics.py
tests/zenko_e2e/cloudserver/test_backend.py
tests/zenko_e2e/cloudserver/test_crr_retry.py
tests/zenko_e2e/cloudserver/test_encryption.py
tests/zenko_e2e/cloudserver/test_lifecycle.py
tests/zenko_e2e/cloudserver/test_location_constraints.py
tests/zenko_e2e/cloudserver/test_metadata.py
tests/zenko_e2e/cloudserver/test_mpu.py
tests/zenko_e2e/cloudserver/test_replication.py
tests/zenko_e2e/conf.py
tests/zenko_e2e/fixtures/backend.py
tests/zenko_e2e/fixtures/bucket.py
tests/zenko_e2e/fixtures/data.py
tests/zenko_e2e/fixtures/lifecycle.py
tests/zenko_e2e/fixtures/misc.py
tests/zenko_e2e/fixtures/object.py
tests/zenko_e2e/fixtures/replication.py
tests/zenko_e2e/prometheus/client.py
tests/zenko_e2e/util/azure.py
tests/zenko_e2e/util/bucket.py
tests/zenko_e2e/util/misc.py

some linting rules regarding wildcard imports were disabled to improve readability.
ie to keep
```
from ..fixtures import *
```
from turning into
```
from ..fixtures import (zenko_bucket,
testfile,
objkey,
aws_ep_bucket,
aws_target_bucket,
gcp_ep_bucket,
gcp_target_bucket,
azure_ep_bucket,
azure_target_bucket,
wasabi_ep_bucket,
wasabi_target_bucket,
digital_ocean_ep_bucket,
digital_ocean_target_bucket)
```

chore: ZENKO-651 Fix formatting and enable linting for e2e tests

---

charts/zenko-filer/templates/service.yaml
charts/zenko-filer/values.yaml

This changes Zenko Filer service type to NodePort. Even though this is not the final or ideal way of exposing the service, it's better than ClusterIP because it allows exposing the service outside the Kubernetes Cluster without having to do port-forwarding to the pods.
Additionally, image tags have been updated to 8.0.0 to follow the version pattern that other components have.

chore: zenko-filer NodePort service

---

charts/cloudserver-front/templates/_helpers.tpl
charts/cloudserver-front/templates/deployment.yaml
charts/cloudserver-front/values.yaml
eve/ci-values.yml

This removes ci configuration from the user observable part of the charts. Instead, CI is been deployed "like a user" will do.

ci: remove configuration from user-observable part

---

charts/cloudserver-front/templates/deployment.yaml

Thanks to `NODE_EXTRA_CA_CERTS`, we no longer need `HTTPS_PROXY_CERTIFICATE`.

chore: delete unnecessary cert configuration var

---

charts/backbeat/templates/replication/data_processor_deployment.yaml
charts/backbeat/templates/replication/populator_deployment.yaml
charts/backbeat/templates/replication/status_processor_deployment.yaml
charts/backbeat/values.yaml

Add "replication" to pod names to avoid confusions, and change
"producer" and "consumer" to more meaningful names.
New pod names:
- backbeat-producer -> backbeat-replication-populator
- backbeat-consumer -> backbeat-replication-data-processor
- backbeat-status -> backbeat-replication-status-processor
If there's a risk it does not fit anymore in DNS name limit (63 char?)
we can consider shortening names, but ideally (to me) they would be as
self-descriptive as they can get.

rf: ZENKO-758 rename replication pods

---

tests/zenko_e2e/backbeat/package-lock.json
tests/zenko_e2e/backbeat/tests/api/healthchecks.js
tests/zenko_e2e/backbeat/tests/api/metrics.js
tests/zenko_e2e/backbeat/utils/request.js

most additions are from package-lock file  x.x

ft: ZENKO-740 add e2e tests crr metrics/healthcheck

---

charts/zenko/values.yaml
eve/ci-values.yml
eve/main.yml
tests/zenko_e2e/conftest.py
tests/zenko_e2e/grafana/test_dashboard.py
tests/zenko_e2e/grafana/test_datasource.py

The Grafana tests were disabled because its chart was not installing in CI due to privilege issues. The Grafana sidecar image has been updated to a custom one that does not have privilege implications and now it is possible to install Grafana on CI and run the tests for it.

ci: re-enable grafana tests

---

charts/cloudserver/templates/deployment.yaml
charts/cloudserver/templates/manager-deployment.yaml
charts/cloudserver/values.yaml

Sets up a default soft anti affinity for the cloudserver chart

ft: cloudserver soft anti-affinity

---

charts/single-node-values.yml
charts/zenko/values.yaml
eve/ci-values.yml
eve/main.yml

- Modify number of kafka partitions created to nodeCount
- Set all scalable backbeat components replica count to nodeCount

ft: ZENKO-781 scale out backbeat services

---

charts/backbeat/templates/api/deployment.yaml
charts/backbeat/templates/configmap.yaml
charts/backbeat/templates/gc/deployment.yaml
charts/backbeat/templates/ingestion/consumer_deployment.yaml
charts/backbeat/templates/ingestion/producer_deployment.yaml
charts/backbeat/templates/lifecycle/bucket_processor_deployment.yaml
charts/backbeat/templates/lifecycle/conductor_deployment.yaml
charts/backbeat/templates/lifecycle/object_processor_deployment.yaml
charts/backbeat/templates/replication/data_processor_deployment.yaml
charts/backbeat/templates/replication/populator_deployment.yaml
charts/backbeat/templates/replication/status_processor_deployment.yaml
charts/backbeat/values.yaml
charts/cloudserver/templates/_env.tpl
charts/cloudserver/templates/accounts.yaml
charts/cloudserver/templates/configmap.yaml
charts/cloudserver/templates/deployment.yaml
charts/cloudserver/templates/manager-deployment.yaml
charts/cloudserver/templates/secrets.yaml
charts/cloudserver/templates/tests/cloudserver-test.yaml
charts/cloudserver/values.yaml
charts/setup-no-orbit.md
charts/single-node-values.yml
charts/zenko/templates/secrets.yaml
charts/zenko/values.yaml
eve/ci-values.yml
images/tools/Dockerfile

- Support for using different cloud backends.
- Replication.
- Multiple Cloudserver users.
Instrucctions on the setup can be found in ```charts/setup-no-orbit.md```.
If related configuration values are changed in ```values.yml```, a ```helm dependency build zenko && helm upgrade zenko zenko``` command (assuming zenko is the release name) will restart the pods with the updated configuration.

feat: extend support without orbit
