- swarm-production/README.md
- swarm-production/docker-stack.yml
This removes the need to pre-create directories for docker volumes.
> Dynamic volumes

- swarm-testing/docker-stack.yml
> Fix upstream for testing swarm stack

- images/nginx-lb/nginx.conf.template
- swarm-production/README.md
- swarm-production/docker-stack.yml
- swarm-production/secrets.txt
Adds support for configuring the endpoint, and changing credentials via docker secrets.
Needs scality/s3#819
> Extra Configuration Values

- README.md
Noticed typo in README intro when browsing Zenko repository. No code changes in this pull request
> fix spelling for Microsoft

- swarm-production/README.md
- swarm-testing/README.md
Update nginx container name, and swarm-production/README file size in
bash examples.
> DOC: update nginx container name

- swarm-production/docker-stack.yml
Ports in docker-stack.yml are swapped between data and metadata.
> use correct ports

- swarm-production/docker-stack.yml
goes with https://github.com/scality/backbeat/pull/147
> FT: Update kafka topic for 1 populator

- .eslintrc
- .gitignore
- package.json
- swarm-production/README.md
- swarm-production/docker-stack.yml
- tests/clueso-tests/basicSearch.js
- tests/clueso-tests/versionEnabledSearch.js
- tests/utils/helpers.js
- tests/utils/s3SDK.js
To-do in docker-stack.yml:
Update the scality/s3server image tag
Update the management endpoint url
This is a rebased + squashed branch for the branch [lhs/clueso-meld](https://github.com/scality/Zenko/tree/lhs/clueso-meld) for merging into master
> ft: clueso meld

- helm/zenko/charts/cloudserver-front/templates/deployment.yaml
- helm/zenko/charts/cloudserver-front/values.yaml
- helm/zenko/charts/zookeeper/values.yaml
> various minor stuff

- swarm-production/docker-stack.yml
Includes support for wasabi backend, and reporting data cleanup.
> Upgrade to new cloudserver snapshot

- swarm-production/docker-stack.yml
> Remove metadata search stack for now

- charts/cloudserver-front/values.yaml
bump cloudserver image tag (fixes MD search)
> bump cloudserver image tag (fix MD search)

- charts/README.md
- charts/minikube.md
- charts/single-node-values.yml
- charts/zenko/templates/NOTES.txt
Minikube values.yml file for light or single machine deployments. It sets up 1 zookeeper and 3 mongos (minimum for a replicaset).
> Minikube Values

- charts/README.md
- charts/cloudserver-front/templates/deployment.yaml
- charts/cloudserver-front/values.yaml
UPDATED PR:
-Added a debug option to cloudserver helm
-Updated the README for clarification for the custom Orbit endpoint
> Readme Clarifications and Debug options for Cloudserver

- charts/minikube.md
The command to enable ingress is `addons`
> Fixed a typo `addons`

- charts/zenko/templates/ingress.yaml
It was forwarding to 8001 but the service was updated to http - port 80
> Update zenko ingress port to the service port

- charts/kafka/Chart.yaml
- charts/kafka/templates/statefulset.yaml
- charts/kafka/values.yaml
- charts/zenko/requirements.lock
- charts/zenko/requirements.yaml
Allows for kafka replicas to be adjustable from the values.yml
> feat(chart): adjustable kafka replicas

- charts/zenko/values.yaml
PR #91 accidentally changed the ingress value instead of the orbit
value. This corrects the oversight (my fault).
> bf: Reset ingress value and orbit

- README.md
Added a link to the K8s Helm Chart docs for easier discovery.
> Add a link to the Kubernetes Helm Chart docs.

- README.md
Updates stack info to what is currently used and clearly shows information for both the docker swarm stack along with the information for k8s deployments.
> doc: Update relevant information and make clarifications

- charts/backbeat/templates/replication/consumer_deployment.yaml
- charts/backbeat/templates/replication/producer_deployment.yaml
> rf: move backbeat producer and consumer into replication

- charts/backbeat/templates/api/deployment.yaml
- charts/backbeat/values.yaml
goes with https://github.com/scality/backbeat/pull/322
> bf: enabled site level metrics

- charts/backbeat/templates/gc/deployment.yaml
- charts/backbeat/values.yaml
Create a new chart for the Garbage Collector service (internal service
for transient source, and later lifecycle transition policies, abort
MPU, etc.)
> ft: ZENKO-143 chart for backbeat GC

- charts/backbeat/templates/ingestion/consumer_deployment.yaml
- charts/backbeat/templates/ingestion/producer_deployment.yaml
- charts/backbeat/values.yaml
- charts/cloudserver-front/values.yaml
- charts/s3-data/values.yaml
- charts/zenko/values.yaml
This adds backbeat ingestion to the Zenko stack.
> feat: add backbeat ingestion templates

- charts/backbeat/values.yaml
This updates the backbeat image and therefore fixing an issue with the ingestion populator startup.
> bf: ingestion populator startup

- charts/backbeat/values.yaml
Updating image tag for backbeat with the latest fixes as of 07/01/2018
> improvement: Update Backbeat Image tag

- charts/README.md
- charts/cloudserver-front/templates/deployment.yaml
- charts/cloudserver-front/values.yaml
allows for testing with dev orbit endpoints
> ft: ZENKO-645 add additional orbit managment vars

- charts/cloudserver-front/templates/certificate.yaml
- charts/cloudserver-front/templates/deployment.yaml
- charts/cloudserver-front/values.yaml
This allows for the proxy certificates to be passed if necessary.
> bf: allow optional proxy certs

- tests/zenko_e2e/backbeat/ReplicationUtility.js
- tests/zenko_e2e/backbeat/Using.md
- tests/zenko_e2e/backbeat/package-lock.json
- tests/zenko_e2e/backbeat/package.json
- tests/zenko_e2e/backbeat/s3SDK.js
- tests/zenko_e2e/backbeat/tests/crr/awsBackend.js
This PR adds CRR to AWS replication end-to-end tests. For now, I've skipped tests which were previously passing but are not currently in Zenko—these skipped tests require further investigation.
> feature: ZENKO-367 CRR to AWS end-to-end tests

- tests/zenko_e2e/cloudserver/test_mpu.py
- tests/zenko_e2e/cloudserver/test_replication.py
- tests/zenko_e2e/util/bucket.py
Enable retries for AWS, GCP, and increase timeouts for CRR tests
> bf(zenko-772): Improve CI Flakiness

- tests/zenko_e2e/backbeat/tests/api/objectMonitor.js
- tests/zenko_e2e/backbeat/utils/request.js
> bugfix: ZENKO-795 auth backbeat api requests

- charts/backbeat/templates/lifecycle/bucket_processor_deployment.yaml
- charts/backbeat/templates/lifecycle/object_processor_deployment.yaml
- charts/backbeat/values.yaml
Rename:
- producer -> bucketProcessor
- consumer -> objectProcessor
Note: waiting for backbeat image update to bump version number.
> rf: ZENKO-744 rename lifecycle producer and consumer
